name: reports
on:
  push:
    branches:
      - master
      - preproduction
      - dev
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  generate-report:
    name: Generate the assets report
    runs-on: ubuntu-latest
    concurrency:
      group: matrix-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Generate report
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            TARGET_BRANCH="$GITHUB_BASE_REF"
          else
            TARGET_BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          echo "Running for $TARGET_BRANCH branch"
          case "${TARGET_BRANCH}" in
            "main"|"master")
              echo "> Using production"
              export ACUVITY_API_URL="${{ secrets.PROD_URL }}"
              export ACUVITY_NAMESPACE="${{ secrets.PROD_NS }}"
              export ACUVITY_TOKEN="${{ secrets.PROD_TOKEN }}"
              ;;
            "preproduction")
              echo "> Using preproduction"
              export ACUVITY_API_URL="${{ secrets.PREPROD_URL }}"
              export ACUVITY_NAMESPACE="${{ secrets.PREPROD_NS }}"
              export ACUVITY_TOKEN="${{ secrets.PREPROD_TOKEN }}"
              ;;
            "dev")
              echo "> Using dev"
              export ACUVITY_API_URL="${{ secrets.DEV_URL }}"
              export ACUVITY_NAMESPACE="${{ secrets.DEV_NS }}"
              export ACUVITY_TOKEN="${{ secrets.DEV_TOKEN }}"

              ;;
          esac
          # generate
          python generate.py
          # commit files
          git config --global user.email "autogenerate@acuvity.ai"
          git config --global user.name "Acuvity reports"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "[autogenerate]: update reports"
            git push origin HEAD:"$TARGET_BRANCH"
          else
            echo "No changes to commit."
          fi
